version: '3'

networks:
  cadmed-net:
    driver: bridge

services:
  db:
    image: mysql:5.7
    container_name: cadmed_db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=cadmed
      - MYSQL_DATABASE=cadmeddb
      - MYSQL_USER=cadmed
      - MYSQL_PASSWORD=cadmed123
    networks:
      - cadmed-net
  
  app:
    image: diegotesch/phplaravelcli:0.1
    container_name: cadmed_api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    networks:
      - cadmed-net
